### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by veggiepilot** [maxaeon/covid#16]
Work on the responsiveness of our website.

**Comment by X3N0TEK** [comment]
Currently have a desktop version in place and is responsive for most desktop to laptop application uses. I am currenlty finding the best way to get the response we would like from tablet down. i do have the code we can use, but i belive this will too need to be executed with either media queries, js, or it might actually be some more digging within the Bulma Docs. 

I wish to have this competed by the end of the week .
